apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operator-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    type: backend
    {{- include "operator-api.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "operator-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        type: backend
        {{- include "operator-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: OTEL_SERVICE_NAME
              value: Operator-Api({{ .Release.Namespace }})
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: Logging__Console__FormatterName
              value: json
            - name: ConnectionStrings__Tgs
              valueFrom:
                secretKeyRef:
                  name: tgs-connections
                  key: tgs
            - name: ConnectionStrings__RedisConfigurationString
              valueFrom:
                secretKeyRef:
                  name: tgs-connections
                  key: redis
            - name: Email__Url
              valueFrom:
                secretKeyRef:
                  name: tgs-connections
                  key: tgs-email-url
            - name: NatsSetting__Urls
              valueFrom:
                secretKeyRef:
                  name: tgs-connections
                  key: nats
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 3
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 30
            periodSeconds: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config/appsettings.json
              name: appsettings
              readOnly: true
              subPath: appsettings.json
        - name: monitor
          image: otel/opentelemetry-collector:0.62.1
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config=/etc/otel/config.yaml
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - name: metrics
              containerPort: 8889
              protocol: TCP
            - name: health
              containerPort: 13133
              protocol: TCP
            - name: otlp
              containerPort: 4317
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/otel/config.yaml
              name: appsettings
              readOnly: true
              subPath: otel-collector-config.yaml
          startupProbe:
            httpGet:
              path: /healthz
              port: health
            periodSeconds: 2
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: appsettings
          configMap:
            name: configmap-{{ include "operator-api.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
